import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-10 border-b border-neutral-800 bg-[#0f1b2a] text-white">
          <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <img src="/logo.svg" alt="Logo" className="h-8 w-8" />
              <Link href="/" className="font-semibold tracking-wide">QuickShip Courier</Link>
            </div>
            <nav className="hidden md:flex items-center gap-6 text-sm">
              <Link className="hover:text-[#ff8a3d]" href="/">Home</Link>
              <Link className="hover:text-[#ff8a3d]" href="#">Services</Link>
              <Link className="hover:text-[#ff8a3d]" href="/track">Track Package</Link>
              <Link className="hover:text-[#ff8a3d]" href="/login">Customer Portal</Link>
            </nav>
            <div className="flex items-center gap-2">
              <Link href="/login" className="hidden sm:inline-block rounded-md border border-white/20 px-3 py-1.5 text-sm hover:bg-white/10">Login</Link>
              <Link href="/register" className="rounded-md bg-[#ff8a3d] px-3 py-1.5 text-sm font-semibold text-black hover:bg-[#ff7a1f]">Register</Link>
            </div>
          </div>
        </header>
        <main className="max-w-6xl mx-auto px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
